# 전체 posts 목록 조회
GET http://localhost:3000/api/posts

###

#  게시글 상세페이지 조회 API
GET http://localhost:3000/api/posts/16

###

# 게시글 추가 API
POST http://localhost:3000/api/posts
Content-Type: application/json

{
    "name":"hey",
    "title": "이거확인",
    "content": "12234"
}

###
# 게시글 수정 API
PUT  http://localhost:3000/api/posts/8
Content-Type: application/json

{
    "name":"RYU",
    "title": "nodejs",
    "content": "얍"
}

###
#  게시글 삭제 API

DELETE  http://localhost:3000/api/posts/18

###
# 댓글 목록 조회 API

GET http://localhost:3000/api/posts/7/comments

###
# 댓글 작성 API

POST http://localhost:3000/api/posts/7/comments
Content-Type: application/json

{
    "name":"RYU123",
    "comment": "test얍"
}

###
# 댓글 수정 API

PUT  http://localhost:3000/api/posts/8/comments/9
Content-Type: application/json

{
    "name":"won",
    "comment": "테스트테스트"
}

###
# 댓글 삭제 API

DELETE  http://localhost:3000/api/posts/7/comments/8

